# Locator values for register
Url = https://flights.qedgetech.com/
ObjReg = //a[normalize-space()='Register']
ObjName = //input[@id='name']
ObjcNumber = //input[@id='contact']
ObjEmail = //input[@id='email']
Objpass = //input[@id='address']
ObjGender = //select[@name='gender']
ObjDOB = //input[@id='popupDatepicker']
Objcheckbox = //input[@id='flexCheckChecked']
Objregister = //input[@name='submit']
# Testdata for register
EnterName = testing
EnterCnumber = 2356778
EnterEmail = test65we@gmail.com
EnterPass = admin43
SelectGender = Male
EnterDod = 20-3-2000
